# Generated by Django 4.2.19 on 2025-04-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='view_comment',
            field=models.IntegerField(default=0),
        ),
    ]
