# Generated by Django 4.2.19 on 2025-04-28 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_news_view_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='view_comment',
            new_name='view_count',
        ),
    ]
