# Generated by Django 4.2.19 on 2025-04-28 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_rename_view_comment_news_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='view_count',
        ),
    ]
