# Generated by Django 4.2.19 on 2025-04-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_remove_news_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCountNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
